minki:
  comment: Hi! this is "changed" dev land
  description: changed develop land
  
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/project3
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 6639
    swjh: love
